services:
  frontend:
    container_name: instapoll-frontend
    build:
      context: ./frontend
    ports:
      - 80:80
    volumes:
      - ./frontend/src:/usr/share/nginx/html
    environment:
      - API_URL=http://localhost:3000

  backend:
    container_name: instapoll-backend-dev
    build:
      context: ./backend
      target: dev
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NODE_ENV: production
    volumes:
      - ./backend/src:/usr/src/app/src
    env_file:
      - ./backend/.env

  redis:
    container_name: instapoll-redis-dev
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

  swagger:
    container_name: instapoll-swagger-dev
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    environment:
      - SWAGGER_JSON=/api.yaml
    volumes:
      - ./backend/api.yaml:/api.yaml