services:
  - type: web
    name: instapoll
    runtime: docker
    repo: https://github.com/ibrahimhabibeg/InstaPoll
    region: frankfurt
    plan: free
    branch: production
    rootDir: frontend
    envVars:
      - key: API_URL
        value: https://instapoll-backend.onrender.com

  - type: web
    name: instapoll-backend
    runtime: docker
    repo: https://github.com/ibrahimhabibeg/InstaPoll
    region: frankfurt
    plan: free
    branch: production
    rootDir: backend
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: instapoll-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: instapoll-redis
          property: port
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 80
      - key: JWT_SECRET
        value: "sample_secret"

  - type: web
    name: instapoll-swagger
    runtime: docker
    image:
      url: docker.io/swaggerapi/swagger-ui:latest
    region: frankfurt
    plan: free
    branch: production
    envVars:
      - key: SWAGGER_JSON
        value: https://raw.githubusercontent.com/ibrahimhabibeg/InstaPoll/main/backend/api.yaml

  - type: redis
    name: instapoll-redis
    region: frankfurt
    ipAllowList: []
    plan: free
    maxmemoryPolicy: allkeys-lru
